all:
  children:
    controller:
      hosts:
        k0s-1:
    worker:
      hosts:
        k0s-2:
        k0s-3:
        k0s-4:
        k0s-5:
  hosts:
    k0s-1:
      ansible_host: 192.168.64.32
    k0s-2:
      ansible_host: 192.168.64.33
    k0s-3:
      ansible_host: 192.168.64.56
    k0s-4:
      ansible_host: 192.168.64.57
    k0s-5:
      ansible_host: 192.168.64.58
  vars:
    ansible_user: k0s
