---

- hosts: all
  name: Download k0s on all nodes
  gather_facts: yes
  become: yes
  roles:
    - role: download
    - role: prereq

- hosts: controller
  gather_facts: yes
  become: yes
  name: Configure k0s control plane nodes
  roles:
    - role: k0s/controller

- hosts: worker
  become: yes
  name: Configure k0s worker nodes
  roles:
    - role: k0s/worker


