---

    - name: Create a Directory /etc/k0s
      become: true
      file:
        path: /etc/k0s
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Create a Directory /var/lib/k0s
      become: true
      file:
        path: /var/lib/k0s
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create a Directory /usr/libexec/k0s/
      become: true
      file:
        path: /usr/libexec/k0s/
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"