---

- name: Copy k0s service file
  become: true
  register: k0s_worker_service
  template:
    src: k0s.service.j2
    dest: "{{ systemd_dest }}/k0s.service"
    owner: root
    group: root
    mode: 0755

- name: Write the k0s token file on worker
  template:
    src: worker-token.j2
    dest: "{{ k0s_config_dir }}/worker-token"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Enable and check k0s service
  become: true
  systemd:
    name: k0s
    daemon_reload: yes
    state: restarted
    enabled: yes
